### ISSUE TITLE
ledge climb

### ISSUE THREAD

**Issue by Saffandev** [DaveFace/CheekyFPS#2]
In the climb system section ledge climb is not working.
-thanks

**Comment by Dealman** [comment]
As stated by the floating text, it's a work in progress.
![image](https://user-images.githubusercontent.com/7038067/106162273-37876a00-6188-11eb-80ed-87c39441f364.png)

**Edit:**

Looked at it a bit, and it's disabled by default - presumably because it's a WIP. The functionality is there, though. You need to enable vaulting and mantling in the **CheekyParkourComponent**.

You also need to setup your own logic for the actual vaulting and mantling but it's simple enough. Here's a very quick example;  
![image](https://user-images.githubusercontent.com/7038067/106203887-5dc6fd00-61bc-11eb-8643-e64f6b3b41b9.png)

The delay isn't really necessary, but helps visualize what the different locations are for. Also do note for mantling over higher walls, you need to hold space a little as otherwise you'll perform a normal jump.

**Comment by DaveFace** [comment]
Sorry, didn't see this issue until now. As Dealman said this whole system is WIP and I wasn't happy with it, and I don't have time to work on it at the moment, so I've disabled all of it by default.

All of the detection work is there, so it can (reasonably) detect when it should vault or climb as well as the positions it needs to move to, but the movement didn't feel very good.

**Comment by DaveFace** [comment]
Closing this issue just so it doesn't remain in limbo.

I was planning to release a new version of CheekyFPS at some point but I've made the decision not to use Unreal Engine 5 for future projects, so this will remain unfinished.
